name: CI for User Service

on:
  workflow_dispatch:

env:
  SCAN_PATH: '/home/runner/work/robot-shop_h/robot-shop_h/user'
  
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install Node.js dependencies for user service
        working-directory : ${{ env.SCAN_PATH }}
        run: npm install

      - name: Install Snyk CLI
        run: npm install -g snyk

      - name: Authenticate Snyk CLI
        run: snyk auth ${{ secrets.SNYK_TOKEN }}

      - name: Run Snyk test
        working-directory: ${{ env.SCAN_PATH }} 
        run: |
          snyk test --json-file-output=${{ env.SCAN_PATH }}/snyk-report.json || true

      - name: Upload Snyk report for user service
        uses: actions/upload-artifact@v4
        with:
          name: snyk-user-report
          path: ${{ env.SCAN_PATH }}/snyk-report.json
          if-no-files-found: error

