name: CI for User Service

on:
  workflow_dispatch:

env:
  SCAN_PATH: '/home/runner/work/robot-shop_h/robot-shop_h/user'
  
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install Node.js dependencies for user service
        working-directory : ${{ env.SCAN_PATH }}
        run: npm install

      - name: Install Snyk CLI
        run: npm install -g snyk

      - name: Authenticate Snyk CLI
        run: snyk auth ${{ secrets.SNYK_TOKEN }}

      - name: Run Snyk test
        working-directory: ${{ env.SCAN_PATH }} 
        run: |
          snyk test --json-file-output=${{ env.SCAN_PATH }}/snyk-report.json || true

      - name: Upload Snyk report for user service
        uses: actions/upload-artifact@v4
        with:
          name: snyk-user-report
          path: ${{ env.SCAN_PATH }}/snyk-report.json
          if-no-files-found: error

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1

      - name: Build, tag, and push Docker image
        working-directory : ${{ env.SCAN_PATH }}
        env:
          ECR_REGISTRY: ${{ secrets.ECR_REGISTRY }}
          ECR_REPOSITORY: ${{ secrets.ECR_REPOSITORY }}
          IMAGE_TAG: ${{ secrets.IMAGE_TAG || github.sha }}
        run: |
            docker build -t $ECR_REPOSITORY:$IMAGE_TAG .
            docker tag $ECR_REPOSITORY:$IMAGE_TAG $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG
            docker push $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG
  
  
