name: CI for User Service

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install Node.js dependencies for user service
        working-directory : /home/runner/work/robot-shop_h/robot-shop_h/user
        run: npm install

      - name: Install Snyk CLI
        run: npm install -g snyk

      - name: Authenticate Snyk CLI
        run: snyk auth ${{ secrets.SNYK_TOKEN }}

      - name: Run Snyk test
        working-directory: /home/runner/work/robot-shop_h/robot-shop_h/user 
        run: snyk test  --json-file-output=snyk-report.json --exit-code=0

      - name: Upload Snyk report
        uses: actions/upload-artifact@v4
        with:
          name: snyk-report
          path: snyk-report.json

